project:
  - fuel
# For debug. Proceed only limited amount of items in project
trunc_report: 0
cache_dir: cache
use_auth: True
teams:
  python:
    fuel-python
    alekseyk-ru
    dshulyak
    rustyrobot
    ikalnitsky
    nmarkov
    aroma-x
    akislitsky
    kozhukalov
    lux-place
    a-gordeev
  ui:
    fuel-ui
    vkramskikh
    astepanchuk
    bdudko
    kpimenova
    jkirnosova
  library:
    fuel-library
    sgolovatiuk
    xenolog
    adidenko
    raytrac3r
    idv1985
    bogdando
    vkuklin
    sbogatkin
    xdeller
    andreika-mail
    mmaxur
    maxmazurenka
  l2:
    manashkin
    ekozhemyakin
    akolesnikov
    fsoppelsa
  astute:
    fuel-astute
    vsharshov
  osci:
    fuel-osci
    sotpuschennikov
    dburmistrov
    vparakhin
    r0mikiam
    mrasskazov
  qa:
    fuel-qa
    apalkina
    aurlapova
    tatyana-leontovich
    asledzinskiy
    apanchenko-8
    ykotko
  devops:
    fuel-devops
    afedorova
    teran
    acharykov
  us:
    dborodaenko
    rmoe
    xarses
    dreidellhasa
    docaedo
  moslinux:
    mos-linux
    apodrepniy
    kdanylov
    msemenov
    asheplyakov
    asyriy
  mosopenstack:
    mos-neutron
    mos-nova
    mos-horizon
    mos-ceilometer
    mos-oslo
    mos-sahara
    mos-heat
    mos-murano
    iberezovskiy
    e0ne
    dmitrymex
    smurashov
    rpodolyaka
    skolekonov
    vrovachev
    ylobankov
    alexei-kornienko
    aepifanov
    akamyshnikova
    dbelova
    efedorova
    enikanorov
    iyozhikov
    shakhat
    mdurnosvistov
    ruhe
    smelikyan
    skolekonov
    skraynev
    sreshetniak
    tnurlygayanov
    tsufiev-x
    yorik-sar
    teselkin-d
    obondarev
    akuznetsova
  partners:
    fuel-partner
    eshumakher
    izinovik
    gcon-monolake
    igajsin
    moshele
    aviramb
    srogov
    ekorekin
  poland:
    tzn
    salmon
    ksambor
    prmtl
    loles
  external:
    longgeek
    berendt
    jesse-pretorius
    sammiestoel
  other_mirantis:
    zynzel
    vpleshakov
    vdenisov
    nikishov-da
    atarasov
    dtyzhnenko
